version: '3.8'

services:
  # Logcomex Importer API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=ritstest.cnfwdrtgyxew.us-west-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=logcomex
      - DB_USER=sarvesh
      - DB_PASSWORD=Saved6-Hydrogen-Smirk-Paltry-Trimmer
      - API_KEY=n8HPUtVG16Ea5mYi5jvlOYqFyObzTd1ZvXMTjU8s
    volumes:
      - ./exports:/app/exports
    restart: unless-stopped
